### PR TITLE
add a reference to the parent repo in README.md

### PR DESCRIPTION
**Pull request by jacobherrington**
I feel like this change is important. I'm not exactly sure how you want to handle this, but I want to have a discussion about it.

Please drop some feedback here for me @joshua-honig @GeorgeKaraszi, thanks!

### CODE REVIEW

**Comment by joshua-honig** [comment]
Hi Jacob, I was thinking that actually this should be regarded as the true home of the repo going forward, including any issues. I asked @gmacdougall to fork from the original Elevator Up repo just so people browsing through would know that the project was initially supported by Elevator Up (just giving credit to the org). But I was thinking that we would actually update the README over in the EU repo to point here...does that make sense?

**Comment by jacobherrington** [comment]
Okay, but we will need to enable issues on this fork.

https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

Not sure if this is current, but it was the first Google result.

**Comment by kennyadsl** [comment]
I've enabled issues on this repository, I think we can close this one.

**Comment by BravoSimone** [comment]
I agree with Alberto 👍

**Pull request closed without merging**
